### ISSUE TITLE
Link to Haskell-Cafe via pipermail

### ISSUE THREAD

**Issue by chrisdone** [chrisdone/haskellnews#12]
See https://github.com/haskell-infra/hl/issues/63#issuecomment-74420850

**Comment by jwaldmann** [comment]
I was looking into this. I think it is important (haskell-cafe IS NOT a google group) but implementation is going to be ugly. 

The root problem is that mailman (pipermail) does not provide the RSS feed. So it has to be (re-)constructed elsewhere, and this requires some hacks. I'll describe my analysis of the data.

To gather the information, we have to first look at the general archive page https://mail.haskell.org/pipermail/haskell-cafe/ and find the most recent monthly archive. Then we can either download and parse the actual messages (txt file), or walk one of the html pages. Of which "by date" looks good, but - it does not actually contain date information (example: https://mail.haskell.org/pipermail/haskell-cafe/2015-February/date.html ) I think there are hidden timestamps in "by thread" (the digits in the first line, before the dot) but I am not sure.

```
<!--0 01422774919.117945- -->
<LI><A HREF="117945.html">[Haskell-cafe] Template Haskell attempts to load mingw32.dll during	build
</A><A NAME="117945">&nbsp;</A>
<I>Darren Grant
</I>
```
Also I had a technical problem: I could not get `HN.Curl.downloadString` to work reliably (segfaults, badcertfile, etc.) https downloads do work with http-conduit though.
