### ISSUE TITLE
HaskellWiki news links just go to the wiki homepage 

### ISSUE THREAD

**Issue by chrisdone** [chrisdone/haskellnews#13]
@bmillwood wrote:

On the [news page](https://www.haskell.org/news) there is a section for HaskellWiki. When I click on any of the links under it, they just take me to the wiki homepage. They have URLs like [https://www.haskell.org/haskellwiki/index.php?title=Yi/FAQ&diff=59120&oldid=58357](https://www.haskell.org/haskellwiki/index.php?title=Yi/FAQ&diff=59120&oldid=58357) – perhaps those are meant to redirect to the new wiki.haskell.org ones?

They're also all 3 months old, and there's been activity on the wiki younger than that. I can add a separate issue for that, but I thought there's a reasonable chance they're related anyway.

**Comment by gbaz** [comment]
We're getting lot of complaints about this and the related issue -- can we look into it?

**Comment by lwm** [comment]
https://github.com/chrisdone/haskellnews/pull/20 is for this and should be merged?

**Comment by chrisdone** [comment]
Merged #20 and deployed.
