### ISSUE TITLE
Reddit posts no longer update

### ISSUE THREAD

**Issue by beerendlauwers** [chrisdone/haskellnews#19]
Last Reddit update on http://haskellnews.org/grouped was 3 weeks ago.

**Comment by chrisdone** [comment]
Related https://github.com/haskell-infra/hl/issues/155

**Comment by herbertjones** [comment]
The feed at https://www.reddit.com/r/haskell/.rss isn't considered a valid Atom feed due to missing the `/feed/updated` field.  I PM'd the developer in charge of it according to https://www.reddit.com/r/changelog/comments/428vdq/upcoming_reddit_change_switching_from_rss_20_to/.

**Comment by herbertjones** [comment]
The developer says that it's fixed but the change won't be live until Monday.

**Comment by beerendlauwers** [comment]
Any update on this?

**Comment by herbertjones** [comment]
Reddit has been fixed, however, the new format doesn't have a "description" field.  I believe "title" is equivalent.  I created PR #24 to accept either.

**Comment by beerendlauwers** [comment]
@herbertjones' PR was merged, so I'll close this.
