### ISSUE TITLE
GitHub group no longer updates

### ISSUE THREAD

**Issue by herbertjones** [chrisdone/haskellnews#22]
http://haskellnews.org/grouped and https://www.haskell.org/news both are 11 months old in the GitHub section.  Running `stack build && stack exec haskellnews -- haskellnews.conf github` locally shows that the GitHub import code still works, as locally I have GitHub entries less than 30 minutes old.  Perhaps the cronjob that updates github no longer occasionally runs.

**Comment by chrisdone** [comment]
GitHub probably just changed their format again or whatever.

**Comment by lwm** [comment]
Checking both links you provide @herbertjones, it seems to be working again.

Please raise an issue if this comes up again.
