### ISSUE TITLE
Google+ feed in German

### ISSUE THREAD

**Issue by spl** [chrisdone/haskellnews#25]
<img width="556" alt="google-plus-german-example" src="https://cloud.githubusercontent.com/assets/54900/16651330/866e9c4a-4443-11e6-8f14-6d3cfb2a4e3d.png">

I'm guessing this is because the site is hosted in Germany:

```
PING haskellnews.org (176.9.42.8) 56(84) bytes of data.
64 bytes from static.8.42.9.176.clients.your-server.de (176.9.42.8): icmp_seq=1 ttl=43 time=97.7 ms
```

Not that I have any problem with the feed being in German, but I'd guess it would be better to choose your language rather than have it chosen for you by an accident of the host location.

Perhaps adding `?hl=en` to the Google+ Haskell community URL would get you an English feed making it consistent with the rest of the site.

**Comment by chrisdone** [comment]
It's because my server is in Germany, but I'll try the `hl` flag.

**Comment by lwm** [comment]
Thanks @spl, that did the trick!
