### ISSUE TITLE
Reddit section no longer updates

### ISSUE THREAD

**Issue by beerendlauwers** [chrisdone/haskellnews#26]
http://haskellnews.org/grouped - Last Reddit update was three weeks ago. Perhaps a changed JSON schema?

**Comment by chrisdone** [comment]
Probably again.

**Comment by lwm** [comment]
Confirmed.

```
λ  haskellnews [master] ⚡ stack exec haskellnews haskellnews.conf import
("importRedditHaskell","Unable to parse feed from: http://www.reddit.com/r/haskell/.rss")
```

Will take a look at this now.

**Comment by beerendlauwers** [comment]
Does @chrisdone have to restart the instance for it to take effect on http://haskellnews.org/grouped and https://www.haskell.org/news ?

**Comment by lwm** [comment]
Cool. I'll tag master as released. I'll try and come up with something via https://github.com/chrisdone/haskellnews/issues/30.

**Comment by beerendlauwers** [comment]
Reddit feed now seems to be updating again.
