### ISSUE TITLE
Maintainers needed?

### ISSUE THREAD

**Issue by lwm** [chrisdone/haskellnews#27]
I've just started using this feed and it is damn useful. I'd like to help but I see some people already started. With respect to all maintainers because I know you are probably busy, but If I submit a PR, will someone get a chance to review? I see a bunch of issues and small PRs rotting away.  

There are currently 8 contributors and a few more waiting with submitted PRs. Do [contributors get admin/commit access](http://felixge.de/2013/03/11/the-pull-request-hack.html) here? What do you think @chrisdone? 

Related: https://github.com/haskell/cabal/issues/3567.

**Comment by lwm** [comment]
Ping @erantapaa, @relrod, @herbertjones, @dmalikov, @rjregenold, @Daniel-Diaz, @jwaldmann, @rodrigosetti

**Comment by chrisdone** [comment]
I can give you push access, @lwm. Contributors are welcome.

**Comment by lwm** [comment]
Awesome, I'll try to lend a hand around here then!
